<?php
/**
 * User: fabio
 * Date: 04.01.22
 * Time: 18:15
 */

namespace App\Classes\Auphonic;

use Illuminate\Http\Request;
use Illuminate\Support\Facades\Log;
use Spatie\WebhookClient\WebhookConfig;
use Symfony\Component\HttpFoundation\Response;

class ProcessWebhookRespondsTo extends \Spatie\WebhookClient\WebhookResponse\DefaultRespondsTo
{
    public function respondToValidWebhook(Request $request, WebhookConfig $config): Response
    {
        Log::debug("ProcessWebhookRespondsTo::respondToValidWebhook");
        //Log::debug(print_r($request->toArray(), true));

        return parent::respondToValidWebhook($request, $config); // TODO: Change the autogenerated stub
    }
}
